#!/bin/bash
telnet https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjA9Zyii_X5AhXzQkEAHVFtCXIQFnoECAcQAQ&url=https%3A%2F%2Fwww.disneyplus.com%2Fmovies%2Fstar-wars-a-new-hope-episode-iv%2F12fVeZxD2fWJ&usg=AOvVaw2Q2ijZdEYmvR0U7kZ1Al6a
